Read The file and show samples

In [843]:
import pandas as pd
df=pd.read_csv("SuperMarket.csv")
df.head(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.22,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.048,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,NaN,10:37:00 AM,E-wallet,604.17,4.761905,30.2085,5.3

In [844]:
df.sample(2)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
663,641-51-2661,Giza,Naypyitaw,Member,Female,Food and beverages,87.10,10,43.550,914.55,2/12/2019,2:45:00 PM,Credit card,871.00,4.761905,43.550,9.9
110,479-26-8945,Cairo,Mandalay,Member,Female,Sports and travel,16.49,2,1.649,34.629,2/5/2019,11:32:00 AM,Ewallet,32.98,4.761905,1.649,4.6

1.Display columns Name and data types

In [845]:
df.columns

Index(['Invoice ID', 'Branch', 'City', '   Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment    ', '   cogs', 'gross margin percentage',
       'gross income', 'Rating'],
      dtype='object')

In [846]:
df.dtypes

Invoice ID                  object
Branch                      object
City                        object
   Customer type            object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Sales                       object
Date                        object
Time                        object
Payment                     object
   cogs                    float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

check number of nulls for each column

In [847]:
df.isnull().sum()

Invoice ID                  0
Branch                      0
City                        0
   Customer type            0
Gender                      0
Product line                0
Unit price                 24
Quantity                    0
Tax 5%                      0
Sales                      20
Date                       12
Time                        0
Payment                     0
   cogs                     0
gross margin percentage     0
gross income                0
Rating                      0
dtype: int64

chech the numnber of duplicated row

In [848]:
df.duplicated().sum()

14

4 Display basic statistical information.

In [849]:
df.describe()

,Unit price,Quantity,Tax 5%,cogs,gross margin percentage,gross income,Rating
count,990.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000
mean,55.520333,5.502959,15.336872,306.737436,4.761905,15.336872,6.960454
std,26.330508,2.927133,11.685945,233.718896,0.000000,11.685945,1.721264
min,10.080000,1.000000,0.508500,10.170000,4.761905,0.508500,4.000000
25%,33.202500,3.000000,5.864625,117.292500,4.761905,5.864625,5.500000
50%,54.890000,5.000000,12.066000,241.320000,4.761905,12.066000,6.900000
75%,77.667500,8.000000,22.428000,448.560000,4.761905,22.428000,8.475000
max,99.960000,10.000000,49.650000,993.000000,4.761905,49.650000,10.000000

5 Identify any unnecessary or suspicious data

unnecessary data:
columns of -- gross margin percentage , Tax 5% , gross income , -- can be removed later 
cogs columns will be named as Cost of Goods salled

6 Observation before handling the data

1.Sales column type needs to be float
2.Date column type needs to be Datetime
3.There were 24 empty cell for unit price
4.There were 20 empty cell for Sales
5.There were 12 empty cell for Date
6.14 duplicated row needs to be removed
7.names of the columns needs to be handled

1)handling columns and data names

In [850]:
columns=df.columns
for i in columns :
    if df[i].dtype=='object' or df[i].dtype =='string':
        df[(i)]=df[(i)].str.strip()
        df[i]=df[i].str.title()
df.columns=df.columns.str.title()
df.columns=df.columns.str.strip()
df.rename(columns=({'Cogs':'Cost of Goods saled'}),inplace=True)
df.columns

Index(['Invoice Id', 'Branch', 'City', 'Customer Type', 'Gender',
       'Product Line', 'Unit Price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'Cost of Goods saled', 'Gross Margin Percentage',
       'Gross Income', 'Rating'],
      dtype='object')

2)Handling the Data types

In [851]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df.dtypes

Invoice Id                         object
Branch                             object
City                               object
Customer Type                      object
Gender                             object
Product Line                       object
Unit Price                        float64
Quantity                            int64
Tax 5%                            float64
Sales                              object
Date                       datetime64[ns]
Time                               object
Payment                            object
Cost of Goods saled               float64
Gross Margin Percentage           float64
Gross Income                      float64
Rating                            float64
dtype: object

In [852]:
df['Payment']=df['Payment'].str.replace("Ewallet","E-Wallet")

In [853]:
df['Sales']=df['Sales'].str.replace("Egp","")

In [854]:
df['Sales']=df['Sales'].astype("float")
df.dtypes

Invoice Id                         object
Branch                             object
City                               object
Customer Type                      object
Gender                             object
Product Line                       object
Unit Price                        float64
Quantity                            int64
Tax 5%                            float64
Sales                             float64
Date                       datetime64[ns]
Time                               object
Payment                            object
Cost of Goods saled               float64
Gross Margin Percentage           float64
Gross Income                      float64
Rating                            float64
dtype: object

In [855]:
coordinates = df[df == "94.2375EGP"].stack().index.tolist()
print(coordinates)

[]

handling the missing values

In [856]:
df.isnull().sum()

Invoice Id                  0
Branch                      0
City                        0
Customer Type               0
Gender                      0
Product Line                0
Unit Price                 24
Quantity                    0
Tax 5%                      0
Sales                      20
Date                       12
Time                        0
Payment                     0
Cost of Goods saled         0
Gross Margin Percentage     0
Gross Income                0
Rating                      0
dtype: int64

In [857]:
df.columns

Index(['Invoice Id', 'Branch', 'City', 'Customer Type', 'Gender',
       'Product Line', 'Unit Price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'Cost of Goods saled', 'Gross Margin Percentage',
       'Gross Income', 'Rating'],
      dtype='object')

In [858]:
df[df['Unit Price'].isnull() & df["Sales"].isnull()]

Empty DataFrame
Columns: [Invoice Id, Branch, City, Customer Type, Gender, Product Line, Unit Price, Quantity, Tax 5%, Sales, Date, Time, Payment, Cost of Goods saled, Gross Margin Percentage, Gross Income, Rating]
Index: []

In [859]:
df["Unit Price"].isnull().sum()
df["Unit Price"]=df["Unit Price"].fillna((df["Sales"] - df["Tax 5%"]) / (df["Quantity"]))

In [860]:
df['Sales'].isnull().sum()

20

In [861]:
df['Sales']=df['Sales'].fillna((df["Unit Price"] + df["Tax 5%"]) * (df["Quantity"]))

In [862]:
df['Sales'].isnull().sum()

0

In [863]:
df[df['Date'].isnull()]

,Invoice Id,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5%,Sales,Date,Time,Payment,Cost of Goods saled,Gross Margin Percentage,Gross Income,Rating
4,373-73-7910,Alex,Yangon,Member,Female,Sports And Travel,86.31,7,30.2085,634.3785,NaT,10:37:00 Am,E-Wallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic Accessories,85.39,7,29.8865,627.6165,NaT,6:30:00 Pm,E-Wallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,Alex,Yangon,Member,Female,Electronic Accessories,68.84,6,20.6520,433.6920,NaT,2:36:00 Pm,E-Wallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home And Lifestyle,73.56,10,36.7800,772.3800,NaT,11:38:00 Am,E-Wallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,Alex,Yangon,Member,Female,Health And Beauty,36.26,2,3.6260,76.1460,NaT,5:15:00 Pm,Credit Card,72.52,4.761905,3.6260,7.2
9,692-92-5582,Cairo,Mandalay,Member,Female,Food And Beverages,54.84,3,8.2260,172.7460,NaT,1:27:00 Pm,Credit Card,164.52,4.761905,8.2260,5.9
10,351-62-0822,Cairo,Mandalay,Member,Female,Fashion Accessories,14.48,4,2.8960,60.8160,NaT,6:07:00 Pm,E-Wallet,57.92,4.761905,2.8960,4.5
11,529-56-3974,Cairo,Mandalay,Member,Female,Electronic Accessories,25.51,4,5.1020,107.1420,NaT,5:03:00 Pm,Cash,102.04,4.761905,5.1020,6.8
12,365-64-0515,Alex,Yangon,Member,Female,Electronic Accessories,46.95,5,11.7375,246.4875,NaT,10:25:00 Am,E-Wallet,234.75,4.761905,11.7375,7.1
13,252-56-2699,Alex,Yangon,Member,Female,Food And Beverages,43.19,10,21.5950,453.4950,NaT,4:48:00 Pm,E-Wallet,431.90,4.761905,21.5950,8.2
14,829-34-3910,Alex,Yangon,Member,Female,Health And Beauty,71.38,10,35.6900,749.4900,NaT,7:21:00 Pm,Cash,713.80,4.761905,35.6900,5.7
15,299-46-1805,Cairo,Mandalay,Member,Female,Sports And Travel,93.72,6,28.1160,590.4360,NaT,4:19:00 Pm,Cash,562.32,4.761905,28.1160,4.5

In [864]:
df.shape

(1014, 17)

remove dupicataed rows

In [866]:
df=df.drop_duplicates()

remove unnecessary columns

In [867]:
df.drop('Tax 5%', axis=1, inplace=True)
df.drop('Gross Margin Percentage', axis=1, inplace=True)

Adding new columns

In [868]:
df['Day']=df['Date'].dt.day_name()
df['Month']=df['Date'].dt.month_name()
df['Year']=df['Date'].dt.year
df['Date']
df

,Invoice Id,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Sales,Date,Time,Payment,Cost of Goods saled,Gross Income,Rating,Day,Month,Year
0,750-67-8428,Alex,Yangon,Member,Female,Health And Beauty,74.69,7,548.9715,2019-01-05,1:08:00 Pm,E-Wallet,522.83,26.1415,9.1,Saturday,January,2019.0
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic Accessories,15.28,5,80.2200,2019-03-08,10:29:00 Am,Cash,76.40,3.8200,9.6,Friday,March,2019.0
2,631-41-3108,Alex,Yangon,Normal,Female,Home And Lifestyle,46.33,7,340.5255,2019-03-03,1:23:00 Pm,Credit Card,324.31,16.2155,7.4,Sunday,March,2019.0
3,123-19-1176,Alex,Yangon,Member,Female,Health And Beauty,58.22,8,489.0480,2019-01-27,8:33:00 Pm,E-Wallet,465.76,23.2880,8.4,Sunday,January,2019.0
4,373-73-7910,Alex,Yangon,Member,Female,Sports And Travel,86.31,7,634.3785,NaT,10:37:00 Am,E-Wallet,604.17,30.2085,5.3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health And Beauty,40.35,1,42.3675,2019-01-29,1:46:00 Pm,E-Wallet,40.35,2.0175,6.2,Tuesday,January,2019.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home And Lifestyle,97.38,10,1022.4900,2019-03-02,5:16:00 Pm,E-Wallet,973.80,48.6900,4.4,Saturday,March,2019.0
997,727-02-1313,Alex,Yangon,Member,Male,Food And Beverages,31.84,1,33.4320,2019-02-09,1:22:00 Pm,Cash,31.84,1.5920,7.7,Saturday,February,2019.0
998,347-56-2442,Alex,Yangon,Normal,Male,Home And Lifestyle,65.82,1,69.1110,2019-02-22,3:33:00 Pm,Cash,65.82,3.2910,4.1,Friday,February,2019.0
999,849-09-3807,Alex,Yangon,Member,Female,Fashion Accessories,88.34,7,649.2990,2019-02-18,1:28:00 Pm,Cash,618.38,30.9190,6.6,Monday,February,2019.0

In [869]:
df['Year']
df['Year'] = pd.to_datetime(df['Year'], errors='coerce')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Date'] = df['Date'].dt.date

In [870]:
df

,Invoice Id,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Sales,Date,Time,Payment,Cost of Goods saled,Gross Income,Rating,Day,Month,Year
0,750-67-8428,Alex,Yangon,Member,Female,Health And Beauty,74.69,7,548.9715,2019-01-05,1:08:00 Pm,E-Wallet,522.83,26.1415,9.1,Saturday,January,1970-01-01 00:00:00.000002019
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic Accessories,15.28,5,80.2200,2019-03-08,10:29:00 Am,Cash,76.40,3.8200,9.6,Friday,March,1970-01-01 00:00:00.000002019
2,631-41-3108,Alex,Yangon,Normal,Female,Home And Lifestyle,46.33,7,340.5255,2019-03-03,1:23:00 Pm,Credit Card,324.31,16.2155,7.4,Sunday,March,1970-01-01 00:00:00.000002019
3,123-19-1176,Alex,Yangon,Member,Female,Health And Beauty,58.22,8,489.0480,2019-01-27,8:33:00 Pm,E-Wallet,465.76,23.2880,8.4,Sunday,January,1970-01-01 00:00:00.000002019
4,373-73-7910,Alex,Yangon,Member,Female,Sports And Travel,86.31,7,634.3785,NaT,10:37:00 Am,E-Wallet,604.17,30.2085,5.3,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health And Beauty,40.35,1,42.3675,2019-01-29,1:46:00 Pm,E-Wallet,40.35,2.0175,6.2,Tuesday,January,1970-01-01 00:00:00.000002019
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home And Lifestyle,97.38,10,1022.4900,2019-03-02,5:16:00 Pm,E-Wallet,973.80,48.6900,4.4,Saturday,March,1970-01-01 00:00:00.000002019
997,727-02-1313,Alex,Yangon,Member,Male,Food And Beverages,31.84,1,33.4320,2019-02-09,1:22:00 Pm,Cash,31.84,1.5920,7.7,Saturday,February,1970-01-01 00:00:00.000002019
998,347-56-2442,Alex,Yangon,Normal,Male,Home And Lifestyle,65.82,1,69.1110,2019-02-22,3:33:00 Pm,Cash,65.82,3.2910,4.1,Friday,February,1970-01-01 00:00:00.000002019
999,849-09-3807,Alex,Yangon,Member,Female,Fashion Accessories,88.34,7,649.2990,2019-02-18,1:28:00 Pm,Cash,618.38,30.9190,6.6,Monday,February,1970-01-01 00:00:00.000002019

In [871]:
df.sort_values(['Date','Time'],inplace=True)
df

,Invoice Id,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Sales,Date,Time,Payment,Cost of Goods saled,Gross Income,Rating,Day,Month,Year
17,765-26-6951,Alex,Yangon,Member,Female,Sports And Travel,72.61,6,457.4430,2019-01-01,10:39:00 Am,Credit Card,435.66,21.7830,6.9,Tuesday,January,1970-01-01 00:00:00.000002019
970,746-04-1077,Cairo,Mandalay,Member,Female,Food And Beverages,84.63,10,888.6150,2019-01-01,11:36:00 Am,Credit Card,846.30,42.3150,9.0,Tuesday,January,1970-01-01 00:00:00.000002019
839,271-77-8740,Giza,Naypyitaw,Member,Female,Sports And Travel,29.22,6,184.0860,2019-01-01,11:40:00 Am,E-Wallet,175.32,8.7660,5.0,Tuesday,January,1970-01-01 00:00:00.000002019
523,133-14-7229,Giza,Naypyitaw,Normal,Male,Health And Beauty,62.87,2,132.0270,2019-01-01,11:43:00 Am,Cash,125.74,6.2870,5.0,Tuesday,January,1970-01-01 00:00:00.000002019
567,651-88-7328,Alex,Yangon,Normal,Female,Fashion Accessories,65.74,9,621.2430,2019-01-01,1:55:00 Pm,Cash,591.66,29.5830,7.7,Tuesday,January,1970-01-01 00:00:00.000002019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,529-56-3974,Cairo,Mandalay,Member,Female,Electronic Accessories,25.51,4,107.1420,NaT,5:03:00 Pm,Cash,102.04,5.1020,6.8,NaN,NaN,NaT
8,665-32-9167,Alex,Yangon,Member,Female,Health And Beauty,36.26,2,76.1460,NaT,5:15:00 Pm,Credit Card,72.52,3.6260,7.2,NaN,NaN,NaT
10,351-62-0822,Cairo,Mandalay,Member,Female,Fashion Accessories,14.48,4,60.8160,NaT,6:07:00 Pm,E-Wallet,57.92,2.8960,4.5,NaN,NaN,NaT
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic Accessories,85.39,7,627.6165,NaT,6:30:00 Pm,E-Wallet,597.73,29.8865,4.1,NaN,NaN,NaT
14,829-34-3910,Alex,Yangon,Member,Female,Health And Beauty,71.38,10,749.4900,NaT,7:21:00 Pm,Cash,713.80,35.6900,5.7,NaN,NaN,NaT

In [872]:
df['Satisfaction']=df['Rating'].apply(lambda Rating : "Satisfied" if Rating >=7 else "not Satisfied")

In [873]:
df

,Invoice Id,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Sales,Date,Time,Payment,Cost of Goods saled,Gross Income,Rating,Day,Month,Year,Satisfaction
17,765-26-6951,Alex,Yangon,Member,Female,Sports And Travel,72.61,6,457.4430,2019-01-01,10:39:00 Am,Credit Card,435.66,21.7830,6.9,Tuesday,January,1970-01-01 00:00:00.000002019,not Satisfied
970,746-04-1077,Cairo,Mandalay,Member,Female,Food And Beverages,84.63,10,888.6150,2019-01-01,11:36:00 Am,Credit Card,846.30,42.3150,9.0,Tuesday,January,1970-01-01 00:00:00.000002019,Satisfied
839,271-77-8740,Giza,Naypyitaw,Member,Female,Sports And Travel,29.22,6,184.0860,2019-01-01,11:40:00 Am,E-Wallet,175.32,8.7660,5.0,Tuesday,January,1970-01-01 00:00:00.000002019,not Satisfied
523,133-14-7229,Giza,Naypyitaw,Normal,Male,Health And Beauty,62.87,2,132.0270,2019-01-01,11:43:00 Am,Cash,125.74,6.2870,5.0,Tuesday,January,1970-01-01 00:00:00.000002019,not Satisfied
567,651-88-7328,Alex,Yangon,Normal,Female,Fashion Accessories,65.74,9,621.2430,2019-01-01,1:55:00 Pm,Cash,591.66,29.5830,7.7,Tuesday,January,1970-01-01 00:00:00.000002019,Satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,529-56-3974,Cairo,Mandalay,Member,Female,Electronic Accessories,25.51,4,107.1420,NaT,5:03:00 Pm,Cash,102.04,5.1020,6.8,NaN,NaN,NaT,not Satisfied
8,665-32-9167,Alex,Yangon,Member,Female,Health And Beauty,36.26,2,76.1460,NaT,5:15:00 Pm,Credit Card,72.52,3.6260,7.2,NaN,NaN,NaT,Satisfied
10,351-62-0822,Cairo,Mandalay,Member,Female,Fashion Accessories,14.48,4,60.8160,NaT,6:07:00 Pm,E-Wallet,57.92,2.8960,4.5,NaN,NaN,NaT,not Satisfied
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic Accessories,85.39,7,627.6165,NaT,6:30:00 Pm,E-Wallet,597.73,29.8865,4.1,NaN,NaN,NaT,not Satisfied
14,829-34-3910,Alex,Yangon,Member,Female,Health And Beauty,71.38,10,749.4900,NaT,7:21:00 Pm,Cash,713.80,35.6900,5.7,NaN,NaN,NaT,not Satisfied

Answer the Quesiton

1)total revenue

In [874]:
total_revenue=df['Sales'].sum()
print(f"total revenue is : {total_revenue} EGP")

total revenue is : 325895.23000000004 EGP

2)cities' revenues and most one

In [875]:
total_revenue_by_city=df.groupby("City")['Sales'].sum()
print(f'city revenue \n{total_revenue_by_city}')
total_city_revenue = str(total_revenue_by_city.max() )
total_city_revenue_name = str(total_revenue_by_city.idxmax()) 
print(f'Best selling city is : {total_city_revenue_name} with revenue of {total_city_revenue} EGP')

city revenue
City
Mandalay     106602.3390
Naypyitaw    111745.7945
Yangon       107547.0965
Name: Sales, dtype: float64
Best selling city is : Naypyitaw with revenue of 111745.7945 EGP

In [876]:
total_profit_by_branch=df.groupby("Branch")['Gross Income'].sum()
print(f'Branch profit \n{total_profit_by_branch}')
total_brach_profit = str(total_profit_by_branch.max() )
total_Branch_profit_name = str(total_profit_by_branch.idxmax()) 
print(f'Best selling Branch is : {total_Branch_profit_name} with profit of {total_brach_profit} EGP')

Branch profit
Branch
Alex     5057.1605
Cairo    5057.0320
Giza     5265.1765
Name: Gross Income, dtype: float64
Best selling Branch is : Giza with profit of 5265.1765 EGP

In [878]:
total_revenue_by_product_category=df.groupby("Product Line")['Sales'].sum()
print(f'Product revenue\n{total_revenue_by_product_category}')
total_Product_revenue = str(total_revenue_by_product_category.max() )
total_Product_revenue_name = str(total_revenue_by_product_category.idxmax()) 
print("==============")
total_profit_by_product_category=df.groupby("Product Line")['Gross Income'].sum()
print(f'Product profit\n{total_profit_by_product_category}')
total_product_profit = str(total_profit_by_product_category.max() )
total_product_profit_name = str(total_profit_by_product_category.idxmax()) 
print(f'Best profit Product Line is : {total_product_profit_name} with profit of {total_product_profit} EGP')
print(f'Best revenue Product Line is : {total_Product_revenue_name} with profit of {total_Product_revenue} EGP')

Product revenue
Product Line
Electronic Accessories    54738.0555
Fashion Accessories       54731.8500
Food And Beverages        56562.0600
Health And Beauty         49564.8250
Home And Lifestyle        54544.3290
Sports And Travel         55754.1105
Name: Sales, dtype: float64
==============
Product profit
Product Line
Electronic Accessories    2587.5015
Fashion Accessories       2585.9950
Food And Beverages        2673.5640
Health And Beauty         2342.5590
Home And Lifestyle        2564.8530
Sports And Travel         2624.8965
Name: Gross Income, dtype: float64
Best profit Product Line is : Food And Beverages with profit of 2673.564 EGP
Best revenue Product Line is : Food And Beverages with profit of 56562.06 EGP

In [879]:
total_spend_customer_type=df.groupby("Customer Type")['Sales'].sum()
print(f'Product revenue\n{total_spend_customer_type}')
cutomer_spend_more = str(total_spend_customer_type.max() )
total_cutomer_spend_more_name = str(total_spend_customer_type.idxmax()) 
print(f'customer spend more is : {total_cutomer_spend_more_name} with total spend: {cutomer_spend_more} EGP')

Product revenue
Customer Type
Member    192623.245
Normal    133271.985
Name: Sales, dtype: float64
customer spend more is : Member with total spend: 192623.245 EGP

In [880]:
payment_method=df['Payment'].value_counts()
print(payment_method)
most_method=df['Payment'].max()
most_method_amount=payment_method.max()

print(f"most popular method used is : {most_method} with {most_method_amount} processes")

Payment
E-Wallet       345
Cash           344
Credit Card    311
Name: count, dtype: int64
most popular method used is : E-Wallet with 345 processes

In [881]:
average= df['Sales'].mean()
print(f"The average transaction value is: {average:.2f} EGP")

The average transaction value is: 325.90 EGP

In [882]:
customer_Branch=df['Branch'].value_counts()
print(customer_Branch)
cutomer_satisfy=df.groupby("Branch")["Satisfaction"].value_counts()
satisfied_customer=(df[df['Satisfaction']=='Satisfied'])["Branch"].value_counts()
print(satisfied_customer)
print(f'percentage of satisfaction for each branch is : \n{satisfied_customer/customer_Branch}')
max_sat=(satisfied_customer/customer_Branch).idxmax()
print(f"Branch with most percent of satisfication is : {max_sat}")

Branch
Alex     340
Cairo    332
Giza     328
Name: count, dtype: int64
Branch
Alex     179
Giza     171
Cairo    151
Name: count, dtype: int64
percentage of satisfaction for each branch is :
Branch
Alex     0.526471
Cairo    0.454819
Giza     0.521341
Name: count, dtype: float64
Branch with most percent of satisfication is : Alex

In [883]:
total_revenue_by_day =df.groupby("Day")['Sales'].sum()
total_revenue_by_month =df.groupby("Month")['Sales'].sum()
highest_sales_day =total_revenue_by_day.max()
highest_sales_day_name =total_revenue_by_day.idxmax()
highest_sales_month =total_revenue_by_month.max()
highest_sales_month_name =total_revenue_by_month.idxmax()
print(total_revenue_by_day)
print(total_revenue_by_month) 
print(f'highest_sales_day is  {highest_sales_day_name} with revenue of {highest_sales_day}') 
print(f'highest_sales_month is  {highest_sales_month_name} with revenue of {highest_sales_month}')

Day
Friday       42549.8940
Monday       37263.7245
Saturday     56127.5325
Sunday       44698.9415
Thursday     45711.1400
Tuesday      50974.6050
Wednesday    43644.5670
Name: Sales, dtype: float64
Month
February     95554.6030
January     117123.2130
March       108292.5885
Name: Sales, dtype: float64
highest_sales_day is  Saturday with revenue of 56127.5325
highest_sales_month is  January with revenue of 117123.213

In [884]:
over_all_customer=df['Branch'].count()
over_all_satisfied=(df['Satisfaction']=='Satisfied').sum()/over_all_customer
print(f"over_all_satisfied percentage is {over_all_satisfied *100} %")

over_all_satisfied percentage is 50.1 %

In [885]:
df.to_csv("SuperMarket_modified.csv" ,index=False)